# This is a basic workflow to help you get started with Actions

name: Build Code-OSS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: microsoft/vscode

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev
          for i in {1..5}; do # try 5 times
            npm ci && break
            if [ $i -eq 5 ]; then
              echo "Npm install failed too many times" >&2
              exit 1
            fi
            echo "Npm install failed $i, trying again..."
          done

      - name: Build
        run: |
          yarn gulp vscode-web
          ARCHIVE_PATH=".build/web/vscode-web.tar.gz"
          mkdir -p $(dirname $ARCHIVE_PATH)
          tar --owner=0 --group=0 -czf $ARCHIVE_PATH -C .. vscode-web

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Build Artifact
          path: .build/web/vscode-web.tar.gz
      
